FROM node:18.13-alpine3.16 as pre-build

WORKDIR /app

COPY . /app/

RUN npm i --legacy-peer-deps

# ENTRYPOINT npm start
RUN npm run build

FROM nginx:1.23.3-alpine

COPY --from=pre-build /app/build /usr/share/nginx/html